### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by flywire** [Ansuel/Decrypt_RBI_Firmware_Utility#7]
Getting similar error for [Technicolor Firmware Repository](https://whirlpool.net.au/wiki/hack_technicolor#hw_model_1622) VANT-Y and VBNT-J firmwares. VANT-F and VANT-6 tested OK.

Microsoft Windows [Version 10.0.17763.557]
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)

java -jar C:\Users\User\Downloads\Decrypt_RBI_Firmware_Utility.jar
Version 1.5-373a135

```
Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.io.ByteArrayOutputStream.grow(Unknown Source)
        at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
        at java.io.ByteArrayOutputStream.write(Unknown Source)
        at main.file_util.inflatePayload(file_util.java:149)
        at main.file_util.processFile(file_util.java:46)
        at main.button_listners.lambda$new$2(button_listners.java:67)
        at main.button_listners$$Lambda$68/29343429.handle(Unknown Source)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8411)
        at javafx.scene.control.Button.fire(Button.java:185)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)

[pressed Ctrl+C]

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x149c6c00 nid=0x2bc0 runnable [0x00000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x149a5800 nid=0x9dc waiting on condition [0x00000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x149a4800 nid=0x2af0 runnable [0x00000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x1499c000 nid=0x2b2c waiting on condition [0x00000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x1499a400 nid=0x1f34 in Object.wait() [0x14c9f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x09995f78> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x09995f78> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x14984400 nid=0x8ec in Object.wait() [0x14c0f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x09996118> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        - locked <0x09996118> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" #1 prio=5 os_prio=0 tid=0x0234c400 nid=0x4a8 waiting on condition [0x007df000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x09996120> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
        at java.util.concurrent.CountDownLatch.await(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:200)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:143)
        at javafx.application.Application.launch(Application.java:191)
        at main.Main.main(Main.java:13)

"VM Thread" os_prio=2 tid=0x0231c800 nid=0x274c runnable

"VM Periodic Task Thread" os_prio=2 tid=0x149d2400 nid=0x2b78 waiting on condition

JNI global references: 786

Heap
 def new generation   total 78656K, used 4223K [0x04400000, 0x09950000, 0x09950000)
  eden space 69952K,   6% used [0x04400000, 0x0481fda8, 0x08850000)
  from space 8704K,   0% used [0x08850000, 0x08850000, 0x090d0000)
  to   space 8704K,   0% used [0x090d0000, 0x090d0000, 0x09950000)
 tenured generation   total 174784K, used 130421K [0x09950000, 0x14400000, 0x14400000)
   the space 174784K,  74% used [0x09950000, 0x118ad7e0, 0x118ad800, 0x14400000)
 Metaspace       used 11570K, capacity 12276K, committed 12288K, reserved 12672K
```

**Comment by LuKePicci** [comment]
Check which is your default max/min JVM heap size: https://stackoverflow.com/questions/4667483/how-is-the-default-java-heap-size-determined

Then try to increment and see how it goes: https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

You need at least twice the size of the inflated firmware image.

**Comment by flywire** [comment]
Initial 16 MB
Final 256 MB

```
C:\Users\User>java -XX:+PrintFlagsFinal -version | findstr HeapSize
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 67108864                            {product}
    uintx InitialHeapSize                          := 16777216                            {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 268435456                           {product}
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)
```

`java -Xmx384m -jar Decrypt_RBI_Firmware_Utility.jar` works with `vant-y_CRF691-17.2.0188-820-RA.rbi`

`-Xmx300m` is not big enough.

**Comment by LuKePicci** [comment]
This is from my tablet (initial 128M, final 2G):
```
>java -XX:+PrintFlagsFinal -version | findstr HeapSize
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 134217728                           {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 2124414976                          {product}
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

See if switching to 64-bit java lets you avoid the bug without any heap size tweaks.

**Comment by LuKePicci** [comment]
current version streams whatever needs to process, this issue is definitely solved
